name: CI

on:
  push:
    branches:
      - master

jobs:
  g8Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.5
      - name: g8Test
        run: sbt g8Test
      - name: compilation test
        run: cd target/sbt-test/mill-seed/scripted/ && mill __.compile
